package com.xjh.myspringboot.mapper;

import com.xjh.myspringboot.enetity.CacheEmp;

public interface CacheEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    int insert(CacheEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    int insertSelective(CacheEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    CacheEmp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CacheEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_emp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CacheEmp record);

    CacheEmp queryEmpByKeyword(String keywword);
}