package com.xjh.myspringboot.mapper;

import com.xjh.myspringboot.enetity.CacheDept;

public interface CacheDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    int insert(CacheDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    int insertSelective(CacheDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    CacheDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CacheDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CacheDept record);
}