package com.xjh.myspringboot.mapper;

import com.xjh.myspringboot.enetity.Emply;

public interface EmplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int insert(Emply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int insertSelective(Emply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    Emply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Emply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Emply record);
}